# Generated by Django 4.0.3 on 2022-03-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Matter',
        ),
    ]
